#!/bin/bash

cython vector.pyx || exit 1
gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -I/usr/include/python2.7 -o vector.so vector.c || exit 1
pylint *.py && flake8 *.py && nosetests *.py
