#!/bin/bash

case "$(uname -s)" in
    Linux*)
      -I/usr/include/python2.7
    ;;
    Darwin*)
      INCL=-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
      # LDSHARED="mpicc -bundle -undefined dynamic_lookup -DOMPI_IMPORTS"
      LDSHARED="-undefined dynamic_lookup -DOMPI_IMPORTS"
    ;;
    CYGWIN*)    ;;
    MINGW*)     ;;
    *)          machine="UNKNOWN:${unameOut}"
esac

cython vector.pyx || exit 1
gcc -shared -pthread -fPIC -fwrapv -O2 -Wall \
  -fno-strict-aliasing ${LDSHARED} ${INCL} -o vector.so vector.c || exit 1
pylint *.py && flake8 *.py && nosetests *.py
